### ISSUE TITLE
Unable to install awsu

### ISSUE THREAD

**Issue by jonerer** [kreuzwerker/homebrew-taps#7]
Hello!

Thanks for the awesome tools! Awsu is super helpful.

Right now there's an issue with installation thoug. This issue might be related to #6 . When I try to install awsu using brew, the process is to do `brew tap kreuzwerker/taps`, but that results in

```
$ brew tap kreuzwerker/taps -v
==> Tapping kreuzwerker/taps
git clone https://github.com/kreuzwerker/homebrew-taps /usr/local/Homebrew/Library/Taps/kreuzwerker/homebrew-taps --origin=origin --template=
Cloning into '/usr/local/Homebrew/Library/Taps/kreuzwerker/homebrew-taps'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 59 (delta 0), reused 0 (delta 0), pack-reused 56
Receiving objects: 100% (59/59), 12.06 KiB | 398.00 KiB/s, done.
Resolving deltas: 100% (24/24), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/kreuzwerker/homebrew-taps/m1-terraform-provider-helper.rb
formulae require at least a URL
Error: Cannot tap kreuzwerker/taps: invalid syntax in tap!
```

**Comment by mavogel** [comment]
Hi, this seems to be related to #6. Will fix it later this week and keep you posted

**Comment by jonerer** [comment]
Thanks @mavogel our workaround is to just grab the binary and copy it into a folder on the path instead of using brew at all.
Thankfully golang binaries are super easy to work with

**Comment by mavogel** [comment]
Fixed in https://github.com/kreuzwerker/m1-terraform-provider-helper/commit/ac0719515d3cd66d6585c7aa5c74d7416fc0d88c

Please re-open if this bug persists :) Sorry for the inconvenience
